# Generated by Django 2.0.6 on 2018-07-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcutos',
            fields=[
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actulizado', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_control', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('almacen', models.CharField(blank=True, default='Centro', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
