# Generated by Django 2.0.6 on 2018-07-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcutos',
            options={'verbose_name_plural': 'Prodcutos'},
        ),
    ]
