# Generated by Django 2.0.6 on 2018-07-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180705_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcutos',
            new_name='Productos',
        ),
    ]
