# Generated by Django 2.0.6 on 2018-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180705_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
    ]
