# Generated by Django 2.0.6 on 2018-07-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180706_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
