# Generated by Django 2.0.6 on 2019-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20190227_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='estilo',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='none', upload_to='static/img/productos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='almacen',
            field=models.CharField(blank=True, default='Centro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='no_control',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
