# Generated by Django 2.0.6 on 2019-02-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20190228_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='publico',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'Niño'), ('U', 'Unisex')], max_length=100),
        ),
    ]
