# Generated by Django 2.0.6 on 2018-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actulizado', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, default='Durango', max_length=100)),
                ('pais', models.CharField(blank=True, default='Mexico', max_length=100)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
