# Generated by Django 2.0.6 on 2018-07-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_auto_20180706_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
