# Generated by Django 2.0.6 on 2018-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_auto_20180706_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actulizado', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Durango', max_length=100)),
                ('pais', models.CharField(default='Mexico', max_length=100)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
