# Generated by Django 2.0.6 on 2019-02-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_proveedores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
