# Generated by Django 2.0.6 on 2019-02-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('portada', models.ImageField(upload_to='img/catalogos/categoria-productos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
