# Generated by Django 2.0.6 on 2019-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasproductos',
            name='portada',
            field=models.ImageField(upload_to='static/img/catalogos/categoria-productos/'),
        ),
    ]
