# Generated by Django 2.0.6 on 2018-07-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180706_1626'),
        ('productos', '0003_auto_20180706_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Botas',
            new_name='DetalleProducto',
        ),
    ]
