# Generated by Django 2.0.6 on 2019-02-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180706_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/productos/'),
        ),
    ]
