# Generated by Django 2.0.6 on 2019-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/productos/'),
        ),
    ]
