# Generated by Django 2.0.6 on 2019-02-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20190227_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='precio',
        ),
    ]
