# Generated by Django 2.0.6 on 2019-02-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20190228_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='genero',
        ),
    ]
