# Generated by Django 2.0.6 on 2019-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_detalleproducto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='color',
            field=models.CharField(blank=True, choices=[('Negro', 'black'), ('Cafe', 'brown')], max_length=100),
        ),
    ]
