# Generated by Django 2.0.6 on 2019-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20190315_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Negro'), ('brown', 'Cafe'), ('yellow', 'Miel'), ('blue', 'Azul'), ('grey', 'Gris'), ('Red', 'Rojo')], max_length=100),
        ),
    ]
